version: "3"

services:

  # Create container for backend api
  backend:
    image: backend-api
    container_name: app-api
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b :8000 app:app
