version: "3"

services:

  # Create container for backend api
  api:
    image: api
    container_name: app-api
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: gunicorn -w 1 -b :5000 app:app

  # Create container for nginx server
  server:
    image: nginx-server
    container_name: app-server
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
